service: smeagolfy-api

provider:
  name: aws
  runtime: nodejs6.10

functions:
  translator:
    handler: dist/http/endpoints/translator.get
    events:
      - http:
          path: /translator/
          method: get
